# Generated by Django 2.0.1 on 2021-04-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210405_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userentity',
            options={'verbose_name': '客户管理', 'verbose_name_plural': '客户管理'},
        ),
        migrations.AlterField(
            model_name='userentity',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
