# Generated by Django 2.0.1 on 2021-04-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210407_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruitentity',
            options={'ordering': ('id',), 'verbose_name': '水果表', 'verbose_name_plural': '水果表'},
        ),
        migrations.AlterModelOptions(
            name='storeentity',
            options={'ordering': ('create_time',), 'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
        migrations.AlterModelOptions(
            name='userentity',
            options={'ordering': ('id',), 'verbose_name': '客户管理', 'verbose_name_plural': '客户管理'},
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='store', verbose_name='LOGO', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_height',
            field=models.IntegerField(null=True, verbose_name='LOGO高'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='logo_width',
            field=models.IntegerField(null=True, verbose_name='LOGO宽'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='是否开业'),
        ),
        migrations.AddField(
            model_name='storeentity',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='storeentity',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='店号'),
        ),
    ]
