# Generated by Django 2.0.1 on 2021-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210407_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
    ]
