# Generated by Django 2.0.1 on 2021-04-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_fruitentity_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='img',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to='store', verbose_name='水果图片', width_field='img_width'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='img_height',
            field=models.IntegerField(null=True, verbose_name='水果图片高'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='img_width',
            field=models.IntegerField(null=True, verbose_name='水果图片宽'),
        ),
        migrations.AddField(
            model_name='fruitentity',
            name='store_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.StoreEntity', verbose_name='所属店铺'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CateTypeEntity', verbose_name='所属类别'),
        ),
    ]
