# Generated by Django 2.0.1 on 2021-04-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='OrderEntity',
        ),
    ]
