# Generated by Django 2.0.1 on 2021-04-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_realprofile'),
        ('orderapp', '0002_auto_20210409_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartEntity',
            fields=[
                ('no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='购物车编号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='账号')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 't_cart',
            },
        ),
    ]
